#!/usr/bin/env ruby
#
# btmonad
#

#if File.symlink?(__FILE__)
#  require 'pathname'
#  self_file = Pathname.new(__FILE__).realpath
#else
#  self_file = __FILE__ 
#end
#$:.unshift(File.dirname(self_file) + '/lib')

require './btmonad'
Btmonad::Driver.run

