#!/usr/bin/env ruby
#
# rirc -- irc bot with plugin system
#

#if File.symlink?(__FILE__)
#  require 'pathname'
#  self_file = Pathname.new(__FILE__).realpath
#else
#  self_file = __FILE__ 
#end
#$:.unshift(File.dirname(self_file) + '/lib')

require './rirc'
#Rirc.daemon
Rirc::Driver.run

